### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by thoriqazzikraa** [Gabrideiros/lyrics-mus#1]
How to catch if lyrics not found?
I've use try and catch error, but it still shutdown my bot

![Screenshot_2022-04-16-01-06-15-95_61c78dc80ee02b53007c815fefe993e3.jpg](https://user-images.githubusercontent.com/89589243/163626567-b2a6e9f3-3317-484d-85d0-9e164c175a75.jpg)

code :

``` 
    try {
           lyricsq.search(q)
           .then(async (lyric) => {
                 console.log(lyric)
           })
     } catch (err) {
           console.log(err)
     }
```

**Comment by gabrideiros** [comment]
Hi! 👋 Add my Discord: Gabrideiros#1348

Em sex., 15 de abr. de 2022 17:03, Thoriq Azzikra ***@***.***>
escreveu:

**Comment by gabrideiros** [comment]
Use:

(async() => {
	try {
		const lyric = await lyrics.search('Watermelon Sugar');
		console.log(lyric);
	} catch (error) {
		console.log("Unknow lyric.");
	}
})()

**Comment by thoriqazzikraa** [comment]
Great

But i think your module's error
I've tried with popular song but its return error
